### ISSUE TITLE
Panning effects kill the wave and noise channels?

### ISSUE THREAD

**Issue by TrollDecker** [SuperDisk/UGE#101]
Basically, I used a panning effect on a Duty channel and when attempting to play my music back, both the Wave and Noise channels just go completely silent. Remove the effect and they start playing again.

I'm honestly not sure if this is some GB limitation or an actual bug.

**Comment by SuperDisk** [comment]
The 8xx effect isn't so much a pan, as it is a "mute channels selectively on left and right" command, which means you specify the entire left-right layout of the channels as a bit pattern in one single command. 

What 8xx command are you using? I recommend double clicking the effect and using the effect editor since it's difficult to specify bit patterns manually.

**Comment by TrollDecker** [comment]
Aaaah, I think I understand now. I didn't realise it applied it across all channels at once. When I was setting it, I was only checking the ones on the Duty channel I wanted to apply panning to, not realising that by leaving the rest unchecked I was effectively muting those channels.

Apologies for that. 😅

**Comment by SuperDisk** [comment]
All good, I realize it's a little unintuitive but that effect is basically just a reflection of how the GB hardware manages panning :)
