### ISSUE TITLE
Soundtracks (Multi-song files)

### ISSUE THREAD

**Issue by SuperDisk** [SuperDisk/UGE#14]
For integration with a real Gameboy game, there needs to be some way to represent multiple tunes such that they can share instruments/waves/etc.

My ideas for how we could do it:

1. Add multiple order tables into the .UGE format. Regular old tunes would only use one order table. Soundtracks could utilize an order table for each song in their list. Simple solution which would allow for reuse of instruments and waves across each tune. The driver would be configured at runtime which order table to use.

2. Just dump each song separately, with different instruments/waves/etc. Could result in a lot of duplication and wasted space.

The problem is, the GBStudio community enjoys the capability of grabbing existing tunes and dropping them into their game, which is a nice side-effect of GBT having only one hardcoded set of instruments. With option 1, there's no guarantee the songs you grab off the internet are going to play well with each others instruments. With option 2, this is allowed but seems really wasteful space wise. I guess since GBStudio doesn't really care about a bloated ROM to begin with, this approach is feasible. Maybe we could implement both alternatives and just have an option to select which strategy to use.

**Comment by RichardULZ** [comment]
Having one set of instruments sounds great for performance, and a bit for storage, but storage shouldn't be much of an issue if we can properly estimate song lengths, and store them over multiple banks correctly.

I wonder if option 2, despite taking more space, could work better for multi banking songs, as each song would contain their instrument data, no matter what bank you start from.

If you were really smart/dumb, how about banks of instrument banks to load, and during compile when you are fed in the list of songs, you find songs with the same set of instruments, and give them the same instrument bank to load into ram on play...


We currently dedicate 8 banks to music data, that's 8 x 16,383 bytes, enough for 32 reasonable length songs?
Problem we have, we have to supply a bank to GBT converter before we know how big it is, so the main issue right now is organizing songs into banks efficiently, especially 1 pattern long songs people use for sound effects at times.

I'm going to work on a play sound effect system for GBstudio to bash the registers, so that should ease the problem, but how we send the tracks selected in GBstudio back and forward, and integrate them (We have a javascript mod player in there to preview songs), is up in the air.

**Napkin math**
At maximum, you said the instrument data is 180 bytes, (4 bytes on 45 instruments) and 16 bytes per wave, up to another 256... though I assume you're culling those.

Then, 192 minimum bytes per order, with at least 2 orders if you have 1 track with data, and another empty, But, since it's all streamed in a tick at a time, this is not a major concern.

If someone were to make a typical music track in gbt, with every other note used, that's 512 per pattern, with 8 orders/patterns, 4,096 bytes. (every other note is an over estimate, maybe closer to half that again.)
A 1 pattern songs takes 256 bytes minimum, and then an extra 1-2 bytes per note.

In UGE, where patterns are uncompressed, but can be reused, a track like jester, is around 18 patterns for the full version, or 9 for the half version (just 8 orders, loop with a solo).
That means the long one is 3456 bytes, and the short one only half that, not including instruments or data pointers, pretty comparable.

**Comment by SuperDisk** [comment]
Seems like Toxa has solved this issue in https://github.com/untoxa/hUGEBuild (which is now ported over here). Choosing how to assign the instruments and populate the song descriptor can be left up to the user when they integrate the songs into their homebrew (allowing for separate banks of instruments, or using just one).

I'm going to close this issue for now, although if anyone wants to discuss this topic further then please reopen.
