### ISSUE TITLE
macOS Compilation Problems

### ISSUE THREAD

**Issue by jfcaron3** [SuperDisk/UGE#36]
Hello, I am having trouble compiling on macOS 10.13.6.  I have lazarus 2.0.10 installed via MacPorts, I followed the instructions in the README file.  When I get to the lazbuild step, it seems to have a problem with the output directory and where to find files and such.  I am not familiar with lazarus so I don't really know how to fix this.  E.g.:

`Hint: (lazarus) normal output directory of package FCL 1.0.1 is not writable: "/opt/local/share/lazarus/packager/units/x86_64-darwin/"
`
Note: I don't want this directory to be writeable, so I'm not going to run this with sudo.  I'd like to put the files somewhere in my hUGETracker directory.

I'm attaching a text file with the output of `lazbuild hUGETracker.lpi --build-mode="Production Mac" &> output.txt`

Any help is appreciated!
[output.txt](https://github.com/SuperDisk/hUGETracker/files/5936045/output.txt)

**Comment by jfcaron3** [comment]
I removed Lazarus and fpc from MacPorts, deleted ~/.lazarus and installed fpc and Lazarus from the packages at https://sourceforge.net/projects/lazarus/, tried the instructions again.  I think I get the same errors except some of the paths are different because e.g. fpc is in /usr/local/bin instead of /opt/local/bin.  See the output attached to this post.
[output2.txt](https://github.com/SuperDisk/hUGETracker/files/5936211/output2.txt)

**Comment by SuperDisk** [comment]
Hi @jfcaron3, thanks for posting the very useful logs! Actually, I think that hint is benign-- your real problem is this:

```[5.063] /Users/jfcaron/Software/hUGETracker/hUGETracker/mainloop.pas(21,12) Fatal: (10022) Can't find unit machine used by mainloop```

There's a directory in the source called `CPU` that was formerly called `Cpu` as of about 8 hours ago. The project searches for the `CPU` directory to compile units inside it, and on Windows, that has worked because Windows has a case-insensitive file system and `Cpu` and `CPU` are interchangeable. Coincidentally, I renamed the directory to `CPU` just today, which should solve the problem. I'm guessing you must have cloned the project before I made that change.

Sorry for that issue! If you have everything else in place, then re-cloning and compiling should work. I must note though that you will need the `rgbds` binaries on your path (`rgbasm`, `rgblink`, and `rgbfix` specifically) as well as `ffmpeg` if you want to export .wav or .mp3 files.

Once you've successfully compiled the project, build `halt.gb` and `halt.sym` from `halt.asm` like this:

```
rgbasm -ohalt.obj halt.asm
rgblink -ohalt.gb -nhalt.sym halt.obj
rgbfix -p0 -v halt.gb
```

then place `PixeliteTTF.ttf` (from `Resources/Fonts`), `halt.gb`, `halt.sym` and the `hUGEDriver` directory in the same directory as the built binary. Then you should have a "working" copy of the tracker (I put working in quotes because there are still some bugs on Mac-- specifically, font rendering is super slow, so the pattern editor can't display in real-time while playing a song).

I'm working on simplifying this build process significantly, hopefully by tomorrow it should be just a few commands to run and be done-- there's a reason the readme says the process isn't ready to be followed quite yet ;)

I apologize for the super inconvenient process and hope to have Mac binaries available for people very soon, so you won't have to compile anyway.

**Comment by jfcaron3** [comment]
Unfortunately that can't be it.  My CPU folder is all capitals, and my macOS file system is also file-insensitive (default on macOS).  I recloned the repo and tried again, got the same errors. 

On a whim, I did `cp CPU/machine.pas .` in the base directory and tried again, in case it was just a messed up include path or something.  This made the compilation go further but then I got a linking error with SDL2.  I've attached the output4 log from that attempt; I had to compress it because it was way bigger than the previous error logs.  Hopefully that's useful information.

[output4.txt.zip](https://github.com/SuperDisk/hUGETracker/files/5936319/output4.txt.zip)

**Comment by SuperDisk** [comment]
Yeah, you'll need libSDL2 available on your system. I think you can install it with homebrew or macports.

I can also send you a binary .app tomorrow if that fits your needs.

**Comment by jfcaron3** [comment]
Hrm, I do have libsdl2 (2.0.14) installed from MacPorts.  A binary .app would definitely fit my needs, I'm a total beginner (at music in general) and decided to try Gameboy music since my friend is making a homebrew GB game; I'm not looking to develop the tracker itself.

**Comment by SuperDisk** [comment]
I sent a build for mac on Discord.

**Comment by miyuushi** [comment]
Same error on Linux (Ubuntu 21.04 x64). Installed fpc and Lazarus using the .deb files.

**Comment by coffeevalenbat** [comment]
Same error on Ubuntu 20.04 x64, installed lazarus and fpc throught apt

**Comment by SuperDisk** [comment]
@datguywitha3ds, @Skyliegirl33, we've recently added CI to this repo which means that [Linux builds are available now ](https://github.com/SuperDisk/hUGETracker/actions/runs/1156574580) if you'd like to use them.

Alternatively if you'd like to build from source, you can use the [commands found in the CI build script](https://github.com/SuperDisk/hUGETracker/blob/hUGETracker/.github/workflows/build.yml).

As for MacOS, builds are provided, but there's no guarantees as to them yet due to performance issues with font rendering (which will be solved soon hopefully).

**Comment by SuperDisk** [comment]
I'm going to close this issue for now, since you can grab pre-built builds for Linux and Mac from the CI runs, and the [CI build steps](https://github.com/SuperDisk/hUGETracker/blob/hUGETracker/.github/workflows/build.yml) can be followed manually on your machine if you want to build locally.

If any other problems arise or you think this issue shouldn't be closed, please re-open!
