### ISSUE TITLE
Unable to have more than one instance open

### ISSUE THREAD

**Issue by QuinnPainter** [SuperDisk/UGE#40]
If an instance of hUGETracker is already open, trying to open another one does nothing. This seems to be because of output.log, the first instance locks the file and the second instance is unable to open it. Though nothing is ever logged to output, is it even used at all?

**Comment by SuperDisk** [comment]
Good catch-- standard out is redirected to output.log (so basically the result of any print statements). It's mostly just used for debugging since a few error-cases in the tracker (e.g when the clipboard doesn't have valid data, when symbols aren't loaded, etc) print out a warning.

I'll take a look into how to prevent this from causing problems, thanks for reporting!

**Comment by SuperDisk** [comment]
Fixed in e4dfcae. Ultimately I just disabled the "debug log," since the entire reason I started redirecting it to a file in the first place was just to prevent the program from crashing when writing to standard out, not because the log entries are super useful or anything. Debug output is mostly just useful during development and doesn't contain crash information or anything useful. Thank you very much for raising this issue and filing the PR though!
