### ISSUE TITLE
Better Wine Support

### ISSUE THREAD

**Issue by maxoakland** [SuperDisk/UGE#77]
Since there’s not a Mac version, it would be great for the application to work as well in Wine as OpenMPT does

Right now the default songs in the Help menu can be played but open, save, and export windows don’t show the contents of the file system

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/57502156/178820567-fd0abf2a-7a84-4b44-9237-4524009c6360.png">

**Comment by sttng** [comment]
This gets my up-vote or a native macOS Version - preferably to work still on macOS 10.14.6

**Comment by maxoakland** [comment]
> This gets my up-vote or a native macOS Version - preferably to work still on macOS 10.14.6

I’m on 10.14 too! Either one would be great

**Comment by SuperDisk** [comment]
While I do want to support macOS properly, I can't do it via Wine. 

1. I believe Wine isn't supported on Mac anymore, meaning you'd have to use an old version of the OS.
2. Wine is a weird target that isn't well defined-- in the ideal case, anything that works on Windows should also work on Wine, but in practice their implementation isn't entirely correct, and it's impossible to guess what I'd need to do to circumvent their broken implementations.
3. I don't really have a way to test the results of Wine support since I don't own an old Mac that's compatible with Wine.

The correct solution is to distribute a native macOS build. Right now, [the CI builds](https://github.com/SuperDisk/hUGETracker/actions) native Mac versions but they're untested and a little finnicky to get working due to the weird `.app` packaging scheme Apple uses. @sttng has some [pre-built and packaged versions ](https://github.com/sttng/gb-stuff) in his repo which you can check out in the meanwhile.
