### ISSUE TITLE
Can we get a current built ?

### ISSUE THREAD

**Issue by sttng** [SuperDisk/UGE#79]
The most recent release is over a year old (hUGETracker 1.0 Beta 9: (https://github.com/SuperDisk/hUGETracker/releases/tag/1.0b9)https://github.com/SuperDisk/hUGETracker/releases)

Can we get a more recent build ?

**Comment by SuperDisk** [comment]
Hey, thanks for asking; there's been a lot of work and changes since 1.0b9 and my plan is to get some final things wrapped up and release a true 1.0 that's not a beta. In particular, it includes a file format change that I'm coordinating with the GB Studio team so that there's no incompatibility.

If you'd like to try out the snapshot builds, you can go to the Actions tab on GitHub and find the most recent builds on the `hUGETracker` branch.

The latest one is currently this: https://github.com/SuperDisk/hUGETracker/actions/runs/2853837787

**Comment by sttng** [comment]
Thanks for the quick reply and all your effort in this project. Certainly will have a look at the current build.

**Comment by SuperDisk** [comment]
Closing this one with the release of 1.0 Beta 10.
