### ISSUE TITLE
OpenMPT .uge import / export ?

### ISSUE THREAD

**Issue by sttng** [SuperDisk/UGE#80]
I have played around with hUGETracker and OpenMPT a littlebit, and was wondering: Wouldn't it make more sense to rather built .uge support into OpenMPT than to develop a completely new tracker from scratch ? 

The current missing features in OpenMPT I see, are individual channel patterns reuse which I don't think OpenMPT supports (but hUGETracker does) and possibly the effects editor of hUGETracker.

On the win side of things, the UI of OpenMPT is solid, you get some nice features like interpolate effects column, change instrument, change octave, copy paste, etc.

**Comment by SuperDisk** [comment]
> Wouldn't it make more sense to rather built .uge support into OpenMPT than to develop a completely new tracker from scratch ?

It would basically entail gutting the entire playback engine of OpenMPT and replacing it with a GB emulator. It is indeed a nice tracker with a great UI (hUGETracker's design was heavily inspired by it) but fundamentally it's totally different than a chiptune tracker like FamiTracker or hUGETracker.

Additionally, all logic involved with the UGE format, instrument editing, ASM/C export, etc would all have to be rewritten in C++. You'd essentially be replacing almost all of OpenMPT except for the UI layer. It's a totally Herculean task that I don't have the capacity for unfortunately.

> you get some nice features like interpolate effects column, change instrument, change octave, copy paste, etc.

All of those things are currently in hUGETracker already, with the same keybindings as OpenMPT in fact ;) You can even copy/paste between OpenMPT and HT because they share the same clipboard format.

I appreciate the suggestion, but I don't think this is viable. Sorry!

**Comment by sttng** [comment]
Appreciate the feedback and I understand 👍
